#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(BODY_SLAM) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(WILL_O_WISP) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(FIRE_PUNCH) \
    F(THUNDER_PUNCH) \
    F(ICE_PUNCH) \
    F(FIRE_FANG) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(DRAIN_PUNCH) \
    F(LEECH_LIFE) \
    F(ENERGY_BALL) \
    F(AURA_SPHERE) \
    F(FOCUS_BLAST) \
    F(FLASH_CANNON) \
    F(SIGNAL_BEAM) \
    F(CHARGE_BEAM) \
    F(SHADOW_CLAW) \
    F(SHADOW_PUNCH) \
    F(X_SCISSOR) \
    F(NASTY_PLOT) \
    F(PLAY_ROUGH) \
    F(SUPERPOWER) \
    F(ICY_WIND) \
    F(THUNDER_WAVE) \
    F(ANCIENT_POWER) \
    F(SILVER_WIND) \
    F(OMINOUS_WIND) \
    F(ROCK_SLIDE) \
    F(STONE_EDGE) \
    F(BULLDOZE) \
    F(DRAGON_PULSE) \
    F(DRAGON_DANCE) \
    F(WILD_CHARGE) \
    F(POISON_JAB) \
    F(VENOSHOCK) \
    F(PSYSHOCK) \
    F(TRICK_ROOM) \
    F(DAZZLING_GLEAM) \
    F(POWER_UP_PUNCH) \
    F(DARK_PULSE) \
    F(NIGHT_SLASH) \
    F(WEATHER_BALL) \
    F(MUD_SHOT) \
    F(HEAT_WAVE) \
    F(ZEN_HEADBUTT) \
    F(IRON_HEAD) \
    F(MOONBLAST) \
    F(SEED_BOMB) \
    F(EARTH_POWER) \
    F(U_TURN) \
    F(VOLT_SWITCH) \
    F(GIGA_IMPACT)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
